StepInterval: -1
StepMultiplier: 10
StepCount: 10
LogLevel: info
SatelliteDataSource: starlink_6000.tle
SatelliteDataSourceType: tle
GroundStationDataSource: ground_stations.yml
GroundStationDataSourceType: yml
SimulationStartTime: "2026-03-26T14:00:00Z"
